### ISSUE TITLE
Clarify herculesteam-augeasproviders vs domcleal-augeasproviders ?

### ISSUE THREAD

**Issue by BillWeiss** [hercules-team/augeasproviders#137]
Hi there,

I had an old install that I was using domcleal-augeasproviders on.  While looking for updates, I noticed that herculesteam-augeasproviders is the PuppetLabs approved one.  This lead me down the path of seeing what changes I would need to make to move over, where I noticed that they've got the same Project URL (which is where I'm filing this).  If the project has moved to the new namespace, could someone update the README for domcleal's version to say that?  Or, if this is the new version and domcleal's is abandoned, same request.

I _think_, from reading, that domcleal is part of the herculesteam group, but I'm not sure.

Thanks!

**Comment by boogy** [comment]
Hello,

Same here.
Should we replace domcleal-augeasproviders with herculesteam-augeasproviders_X ?

**Comment by beddari** [comment]
The simple answer: Yes :+1:-. hercules-team are the current maintainers of the modules and this is what you should be using!

**Comment by domcleal** [comment]
I've put a big notice at the top of my original module now, I hope that'll suffice!

https://forge.puppetlabs.com/domcleal/augeasproviders#readme
