### ISSUE TITLE
Not possible to add multiple kernel parameters with the same name.

### ISSUE THREAD

**Issue by fhimpe** [hercules-team/augeasproviders#138]
I need to add the kernel parameters console=tty0 console=ttyS0 to my kernel boot options. I tried this:
                        kernel_parameter { "console":
                                value => "tty0",
                        }
                        kernel_parameter { "console":
                                value => "ttyS0",
                        }

But this does not work because I am not allowed to define kenel_parameter["console"] twice.

**Comment by domcleal** [comment]
Pass an array of values instead: `value => ['tty0', 'ttyS0']`

https://github.com/hercules-team/augeasproviders_grub/#manage-parameter-with-multiple-values
http://augeasproviders.com/documentation/examples.html#kernelparameter-provider

**Comment by fhimpe** [comment]
You are right, I just discovered this in the documentation after submitting this. Sorry, I should have checked this earlier.
