### ISSUE TITLE
Split/segregate core library from collection of providers

### ISSUE THREAD

**Issue by reidmv** [hercules-team/augeasproviders#59]
I'm in a situation where I really like the core functionality here, e.g. `include AugeasProviders::Provider`,  but I need to build my own alternate implementations of e.g. `puppet_auth` type and/or provider(s). Is there any way this project could graduate to individual projects based on a central core library published purely as a mixin, a la e.g. http://forge.puppetlabs.com/adrien/filemapper, and individual dependent modules for the specific types/providers that use it?

**Comment by raphink** [comment]
Well the lib was split so this can be closed.
