### ISSUE TITLE
Add autofs provider and type

### ISSUE THREAD

**Issue by jyaworski** [hercules-team/augeasproviders#92]
Is there interest in an autofs provider and type? I have a need for one in my environment, and I feel like this module would be a good place for it.

Currently, I have an idea to implement it as autofs_master and autofs_export.

**Comment by raphink** [comment]
@jyaworski still interested in doing that?

**Comment by jyaworski** [comment]
@raphink I no longer have a facility to test this, so it would likely be best if someone else took it.

**Comment by raphink** [comment]
OK, do you mind if I close this ticket for now then?
